# This is a basic workflow to help you get started with Actions

name: Sanitize BE and FE

# Trigger jobs on...
on: [push, pull_request]

jobs:
  test_FE:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install Node.js dependencies
      run: |
        cd ./ui
        npm install
    - name: Run linters and test for FRONTEND
      run: |
        cd ./ui
        npm run lint
        npm run test
  
  test_BE:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: point_of_sales
          MYSQL_USER: root
          MYSQL_PASSWORD: supersecret
          MYSQL_ROOT_PASSWORD: supersecret
        ports:
          - 33306:3306
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Prepare .env and dependencies
      run: |
        cd ./api
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        composer install --no-scripts
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: |
        cd ./api
        php artisan key:generate
        php artisan migrate
        php artisan test
